### ISSUE TITLE
Compatibility with ViewTransitions

### ISSUE THREAD

**Issue by daklik** [apostrophecms/apostrophe-astro#10]
When using ViewTransitions ([https://docs.astro.build/en/guides/view-transitions/](https://docs.astro.build/en/guides/view-transitions/)), the admin UI disappears when navigating from one page to another - it comes back after a page refresh.

**Comment by daklik** [comment]
@boutell Finally it's very simple to make it compatible.
We just need in the AposEditLayout to add a query parameter to the js bundle src that changes every time.
As then the source is different each time, the browser will load and execute it again.

**Comment by boutell** [comment]
This will reload a large JS bundle on every page load, yes? I realize it's for editors, but still, we should be able to do better... we should be able to get the release id from Apostrophe and incorporate that into the URL.

```
apos.asset.getReleaseId();
```

That would address the possibility of old Apostrophe admin UI assets without reloading them constantly.

But I think you're actually looking to force this code to re-execute on every page load.

I think the question we should be trying to answer is what piece of code really needs to re-execute and why, and how to re-execute it without re-fetching it at considerable expense from the server.
